import fs from 'fs';
import path from 'path';

const REPO_NAME = 'Adventure Forge - Frontend';
const IGNORE_DIRS = ['node_modules', '.git', 'build', 'dist', '.vscode'];

function generateMap(dir, depth = 0) {
    let map = '';
    const files = fs.readdirSync(dir);
    
    files.forEach(file => {
        if (IGNORE_DIRS.includes(file)) return;
        
        const fullPath = path.join(dir, file);
        const stats = fs.statSync(fullPath);
        const indent = '  '.repeat(depth);
        
        if (stats.isDirectory()) {
            map += `${indent}- **${file}/**\n`;
            map += generateMap(fullPath, depth + 1);
        } else if (file.endsWith('.tsx') || file.endsWith('.ts')) {
            map += `${indent}- ${file}\n`;
        }
    });
    return map;
}

const codeMap = `
# CODE_MAP.md - ${REPO_NAME}
*Auto-generated by agent-toolbox*

## Architecture Overview
- **src/common**: Shared services, hooks, contexts, and utilities.
  - **services/ai**: Generators for Text and Audio.
  - **hooks**: \`useGameStream\` for SSE narrative flow.
- **src/views**: Main UI screens (MainMenu, AdventureSelection, Game).
- **src/index.tsx**: Entry point with Providers (Theme, Auth, Settings).

## File Structure
${generateMap('./src')}
`;

fs.writeFileSync('CODE_MAP.md', codeMap);
console.log('✅ CODE_MAP.md generated for Frontend');
